### ISSUE TITLE
shu joyga "background-color:#222; " qilib qo`ying 

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/Article#1]
https://github.com/MIRZOULUGBEK9008/Article/blob/92990f67b96c8d038f38b924a8a8912235ad1c06/css/styles.css#L2

**Comment by MIRZOULUGBEK9008** [comment]
yo'q qilmayman,  sababi  esa mana rasmda ko'rsatilgan
![image](https://user-images.githubusercontent.com/99461357/158434986-f1f507a7-a676-4523-a211-c65b135d55f3.png)
