### ISSUE TITLE
css ni eng quyi qismida bo``ladi bullar

### ISSUE THREAD

**Issue by frontendoniyorbek** [MIRZOULUGBEK9008/Article#4]
https://github.com/MIRZOULUGBEK9008/Article/blob/92990f67b96c8d038f38b924a8a8912235ad1c06/css/styles.css#L51

**Comment by MIRZOULUGBEK9008** [comment]
menimcha bularni farqi yo`q men global stillarda berishim yoki aynan o`zi ishlatilgan joyda berishim mumkin...

**Comment by frontendtester** [comment]
Retina media eng pastda kelishi kerak.
